Create the br-lbaas network automatically
rcbops/rpc-octavia pull request #27
Opened 2018-03-08 16:10 UTC by xgerman

This will create the bridge network, set up the veth pairs,
and use the values to configure a subsequent os-octavia run

2018-03-27 18:36 UTC, whatabout-bob requested changes
It doesn't appear that the script updated the openstack_user_config.yml correctly. On my mnaio deployment, I see where the provider networks section was added to the cidr_networks block, and I don't see any of the other updates (used_ip's, etc) added to the file.  

---
cidr_networks:
# BEGIN ANSIBLE MANAGED BLOCK
- network:
    container_bridge: "br-lbaas"
    container_type: "veth"
    container_interface: "eth14"
    host_bind_override: "eth14"
    ip_from_q: "lbaas"
    type: "raw"
    net_name: "lbaas"
    group_binds:
        - neutron_linuxbridge_agent
        - octavia-worker
        - octavia-housekeeping
        - octavia-health-manager
# END ANSIBLE MANAGED BLOCK
  container: 10.0.236.0/22
  tunnel: 10.0.240.0/22
  storage: 10.0.244.0/22
  flat: 10.0.248.0/22

Also it appears that the host group may be incorrect for the "Setup Octavia network" task, no actions were taken.  Let me know if I can assist with debugging.

2018-03-28 21:27 UTC, whatabout-bob approved these changes

2018-04-02 15:16 UTC, xgerman commented
running checks again --

2018-04-05 15:10 UTC, xgerman commented
recheck_cit_xenial_functional_test

2018-04-06 18:50 UTC, merged