Simplifies the readme
rcbops/rpc-octavia pull request #48
Opened 2018-05-16 19:00 UTC by xgerman

2018-05-16 19:01 UTC, johnsom requested changes

2018-05-31 14:37 UTC, xgerman commented
recheck_xenial_functional_test

2018-05-31 16:09 UTC, xgerman commented
recheck_xenial_functional_test

2018-05-31 19:19 UTC, xgerman commented
recheck_xenial_functional_test

2018-06-04 18:28 UTC, xgerman commented
recheck_xenial_functional_test

2018-06-05 21:43 UTC, johnsom requested changes

2018-06-05 21:43 UTC, johnsom commented on README.md
> +* For Wueens and beyond this repository is retired and installs will be using the upstream OSA os_octavia
Wueens -> Queens

2018-06-05 21:54 UTC, johnsom approved these changes

2018-06-05 22:00 UTC, merged